### ISSUE TITLE
Adjust mailing management

### ISSUE THREAD

**Issue by lfortunier** [smartbooster/sonata-bundle#31]
## Goal

Adjust some part of the mailing management for better implementation

## Steps

- [ ] ~Be able to override email html local for emails sent by symfony command and use `smart_mailer_local` instead of `app.request.getLocale`~
- [x] Add `SmartMailerInterface` for calling `setSender` on all services. Use this interface by compilerPass so as not to have to specify config on mailer child's => add the doc about how to just autowire the missing sender property
- [ ] ~Add `stylesheets` and `wrapper_class` block's in email layout to simplify template override's to add custom fonts~
- [x] Replace namespace SmartAuthentication with SmartSonata on templates/email/{locale}

**Comment by nicolas-bastien** [comment]
This improvement can be done if we have more than one new project with this bundles.

**Comment by mathieu-ducrot** [comment]
@nicolas-bastien the following points haven't resurfaced since there first write :  
- Be able to override email html local for emails sent by symfony command and use smart_mailer_local instead of app.request.getLocale
- Add stylesheets and wrapper_class block's in email layout to simplify template override's to add custom fonts

And for the setSender, we saw with @lfortunier how to fix this. I will mention it on my next PR which will update the mailer doc.

**Comment by mathieu-ducrot** [comment]
setSender issue step handled with according documentation on PR #71 cf. docs/mailer.md
