### ISSUE TITLE
History

### ISSUE THREAD

**Issue by nicolas-bastien** [smartbooster/sonata-bundle#41]
## Use cases

- [ ] EventLog
- [x] EntityLog
- [x] BatchLog

### EventLog

EventLog will centralise log for action which need to be used with statistics.

→ see Oscar

Handle target with targetId and targetClass

**question**

- how to add data on event type ex : customer type for connexion

### EntityLog

- Log each modification on an entity
- + event on the entity not necessarly link to database (ex: stripe modification)
- be able to show entity log for in an admin
- log author of modification (raw text) : username, cron, api...

### BatchLog

Batch log is for logging : cron ,import.... which impact multiples entities.

- an entity with a context : cron, api, import....
- an admin to see log
- in each log a comment which explain to summary
- success of the batch action
- optionnal batch name to better identify which batch it is for a given context

**Comment by mathieu-ducrot** [comment]
@nicolas-bastien Update progress on this issue :
- We now track batch log with the `ProcessInterface` from the [core-bundle](https://github.com/smartbooster/core-bundle)
- Entity diff (mentioned as `EntityLog`) is now automatically track with the `HistorizableInterface` from the [core-bundle](https://github.com/smartbooster/core-bundle)

The only remaining notion `EventLog` do not have a generic equivalent for now.  
All current implementation (ActionLog on ObjectifRGE and OSCAR) are too tightly coupled with the project business logic.

I act that we close this issue since the previous 2 points are done. 

We can talk back about the need for statistics logs from what we already talk about MeasureInterface.
